In [19]:
import pandas as pd
import datetime
from os import listdir
from os.path import isfile, join
import glob
import re

df =pd.read_csv("./data/pew-raw.csv")
df

,religion,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k
0,Agnostic,27,34,60,81,76,137
1,Atheist,12,27,37,52,35,70
2,Buddhist,27,21,30,34,33,58
3,Catholic,418,617,732,670,638,1116
4,Dont know/refused,15,14,15,11,10,35
5,Evangelical Prot,575,869,1064,982,881,1486
6,Hindu,1,9,7,9,11,34
7,Historically Black Prot,228,244,236,238,197,223
8,Jehovahs Witness,20,27,24,24,21,30
9,Jewish,19,19,25,25,30,95

In [20]:
formatted_df =pd.melt(df,
                     id_vars=["religion"],
                     var_name="income",
                     value_name="freq")
formatted_df = formatted_df.sort_values(by="religion")
formatted_df.head(10)

    religion    income  freq
0   Agnostic     <$10k    27
30  Agnostic   $30-40k    81
40  Agnostic   $40-50k    76
50  Agnostic   $50-75k   137
10  Agnostic   $10-20k    34
20  Agnostic   $20-30k    60
41   Atheist   $40-50k    35
21   Atheist   $20-30k    37
11   Atheist   $10-20k    27
31   Atheist   $30-40k    52

In [52]:
df = pd.read_csv("./data/billboard.csv", encoding="mac_latin2")
df.head(10)

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2000,Janet,Doesn't Really Matter,4:17,Rock,2000-06-17,2000-08-26,59,52.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2000,Destiny's Child,Say My Name,4:31,Rock,1999-12-25,2000-03-18,83,83.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2000,"Iglesias, Enrique",Be With You,3:36,Latin,2000-04-01,2000-06-24,63,45.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2000,Sisqo,Incomplete,3:52,Rock,2000-06-24,2000-08-12,77,66.0,61.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,81,54.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
#Melting
id_vars = ["year",
           "artist.inverted",
           "track",
           "time",
           "genre",
           "date.entered",
           "date.peaked"]
df = pd.melt(frame=df, id_vars=id_vars, var_name="week", value_name="rank")

df.head(5)

,year,artist.inverted,track,time,genre,date.entered,date.peaked,week,rank
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,x1st.week,78.0
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,x1st.week,15.0
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,x1st.week,71.0
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,x1st.week,41.0
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,x1st.week,57.0

In [54]:
#Cleaning out unnessary rows
df = df.dropna()

#Formatting
df["week"] = df['week'].str.extract('(\d+)', expand=False).astype(int)

df["rank"] = df["rank"].astype(int)

In [55]:
#Create "Date" columns
df['date'] = pd.to_datetime(df['date.entered']) + pd.to_timedelta(df["week"], unit='w') - pd.DateOffset(weeks=1)
df

,year,artist.inverted,track,time,genre,date.entered,date.peaked,week,rank,date
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,1,78,2000-09-23
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,1,15,2000-02-12
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,1,71,1999-10-23
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,1,41,2000-08-12
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,1,57,2000-08-05
5,2000,Janet,Doesn't Really Matter,4:17,Rock,2000-06-17,2000-08-26,1,59,2000-06-17
6,2000,Destiny's Child,Say My Name,4:31,Rock,1999-12-25,2000-03-18,1,83,1999-12-25
7,2000,"Iglesias, Enrique",Be With You,3:36,Latin,2000-04-01,2000-06-24,1,63,2000-04-01
8,2000,Sisqo,Incomplete,3:52,Rock,2000-06-24,2000-08-12,1,77,2000-06-24
9,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,1,81,1999-06-05
10,2000,N'Sync,It's Gonna Be Me,3:10,Rock,2000-05-06,2000-07-29,1,82,2000-05-06
11,2000,"Aguilera, Christina",What A Girl Wants,3:18,Rock,1999-11-27,2000-01-15,1,71,1999-11-27
12,2000,Vertical Horizon,Everything You Want,4:01,Rock,2000-01-22,2000-07-15,1,70,2000-01-22
13,2000,Creed,With Arms Wide Open,3:52,Rock,2000-05-13,2000-11-11,1,84,2000-05-13
14,2000,Aaliyah,Try Again,4:03,Rock,2000-03-18,2000-06-17,1,59,2000-03-18
15,2000,matchbox twenty,Bent,4:12,Rock,2000-04-29,2000-07-22,1,60,2000-04-29
16,2000,"Carey, Mariah",Thank God I Found You,4:14,Rock,1999-12-11,2000-02-19,1,82,1999-12-11
17,2000,"Hill, Faith",Breathe,4:04,Rap,1999-11-06,2000-04-22,1,81,1999-11-06
18,2000,Mya,Case Of The Ex (Whatcha Gonna Do),3:50,Rock,2000-08-19,2000-12-02,1,72,2000-08-19
19,2000,Dream,He Loves U Not,3:43,Rock,2000-09-30,2000-12-30,1,99,2000-09-30
20,2000,"Braxton, Toni",He Wasn't Man Enough,4:21,Rock,2000-03-18,2000-05-06,1,63,2000-03-18
21,2000,"Anthony, Marc",You Sang To Me,3:50,Latin,2000-02-26,2000-06-03,1,77,2000-02-26
22,2000,98°,Give Me Just One Night (Una Noche),3:24,Rock,2000-08-19,2000-09-30,1,51,2000-08-19
23,2000,Destiny's Child,Jumpin' Jumpin',3:48,Rock,2000-05-13,2000-08-19,1,74,2000-05-13
24,2000,3 Doors Down,Kryptonite,3:53,Rock,2000-04-08,2000-11-11,1,81,2000-04-08
25,2000,Sisqo,Thong Song,4:05,Rock,2000-01-29,2000-05-20,1,74,2000-01-29
26,2000,"Aguilera, Christina",I Turn To You,4:00,Rock,2000-04-15,2000-07-01,1,50,2000-04-15
27,2000,"Houston, Whitney",My Love Is Your Love,4:16,Rock,1999-09-04,2000-01-08,1,81,1999-09-04
28,2000,Joe,I Wanna Know,4:57,Rock,2000-01-01,2000-07-01,1,94,2000-01-01
29,2000,"Jordan, Montell",Get It On.. Tonite,4:34,Rap,1999-10-23,2000-02-12,1,92,1999-10-23
...,...,...,...,...,...,...,...,...,...,...
16184,2000,"Hill, Faith",Breathe,4:04,Rap,1999-11-06,2000-04-22,52,48,2000-10-28
16191,2000,3 Doors Down,Kryptonite,3:53,Rock,2000-04-08,2000-11-11,52,42,2001-03-31
16213,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,52,16,2000-09-02
16493,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,53,20,2000-06-03
16501,2000,"Hill, Faith",Breathe,4:04,Rap,1999-11-06,2000-04-22,53,47,2000-11-04
16508,2000,3 Doors Down,Kryptonite,3:53,Rock,2000-04-08,2000-11-11,53,49,2001-04-07
16530,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,53,17,2000-09-09
16810,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,54,22,2000-06-10
16847,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,54,17,2000-09-16
17127,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,55,22,2000-06-17
17164,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,55,21,2000-09-23
17444,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,56,25,2000-06-24
17481,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,56,26,2000-09-30
17761,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,57,26,2000-07-01
17798,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,57,29,2000-10-07
18078,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,58,31,2000-07-08
18115,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,58,32,2000-10-14
18395,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,59,32,2000-07-15
18432,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,59,39,2000-10-21
18712,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,60,37,2000-07-22
18749,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,60,39,2000-10-28
19029,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,61,42,2000-07-29
19066,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,61,43,2000-11-04
19346,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,62,42,2000-08-05
19383,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,62,47,2000-11-11
19663,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,63,45,2000-08-12
19700,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,63,50,2000-11-18
19980,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,64,50,2000-08-19
20017,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,64,50,2000-11-25
20334,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,65,49,2000-12-02

In [56]:
df = df[["year",
         "artist.inverted",
         "track",
         "time",
         "genre",
         "week",
         "rank",
         "date"
        ]]
df = df.sort_values(ascending=True, by=["year", "artist.inverted", "track", "week", "rank"])
df.head(20)

,year,artist.inverted,track,time,genre,week,rank,date
246,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,1,87,2000-02-26
563,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,2,82,2000-03-04
880,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,3,72,2000-03-11
1197,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,4,77,2000-03-18
1514,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,5,87,2000-03-25
1831,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,6,94,2000-04-01
2148,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,7,99,2000-04-08
287,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,1,91,2000-09-02
604,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,2,87,2000-09-09
921,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,3,92,2000-09-16
24,2000,3 Doors Down,Kryptonite,3:53,Rock,1,81,2000-04-08
341,2000,3 Doors Down,Kryptonite,3:53,Rock,2,70,2000-04-15
658,2000,3 Doors Down,Kryptonite,3:53,Rock,3,68,2000-04-22
975,2000,3 Doors Down,Kryptonite,3:53,Rock,4,67,2000-04-29
1292,2000,3 Doors Down,Kryptonite,3:53,Rock,5,66,2000-05-06
1609,2000,3 Doors Down,Kryptonite,3:53,Rock,6,57,2000-05-13
1926,2000,3 Doors Down,Kryptonite,3:53,Rock,7,54,2000-05-20
2243,2000,3 Doors Down,Kryptonite,3:53,Rock,8,53,2000-05-27
2560,2000,3 Doors Down,Kryptonite,3:53,Rock,9,51,2000-06-03
2877,2000,3 Doors Down,Kryptonite,3:53,Rock,10,51,2000-06-10

In [57]:
#Assigning the tidy dataset to a variable for future usage
billboard = df

df.head(10)

,year,artist.inverted,track,time,genre,week,rank,date
246,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,1,87,2000-02-26
563,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,2,82,2000-03-04
880,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,3,72,2000-03-11
1197,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,4,77,2000-03-18
1514,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,5,87,2000-03-25
1831,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,6,94,2000-04-01
2148,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,7,99,2000-04-08
287,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,1,91,2000-09-02
604,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,2,87,2000-09-09
921,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,3,92,2000-09-16